-- MySQL Script generated by MySQL Workbench
-- qua 27 jul 2022 20:46:05
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema happyPet
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema happyPet
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `happyPet` ;
USE `happyPet` ;

-- -----------------------------------------------------
-- Table `happyPet`.`admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `happyPet`.`admin` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NULL,
  `senha` INT(10) UNSIGNED NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `happyPet`.`categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `happyPet`.`categorias` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `categoria` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `happyPet`.`produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `happyPet`.`produtos` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(60) NOT NULL,
  `preco` FLOAT NOT NULL,
  `descricao` TEXT(500) NOT NULL,
  `categorias_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_produtos_categorias_idx` (`categorias_id` ASC),
  CONSTRAINT `fk_produtos_categorias`
    FOREIGN KEY (`categorias_id`)
    REFERENCES `happyPet`.`categorias` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `happyPet`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `happyPet`.`clientes` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nomeCompleto` VARCHAR(100) NOT NULL,
  `foto` VARCHAR(45) NULL,
  `email` VARCHAR(100) NOT NULL,
  `telefone` VARCHAR(12) NOT NULL,
  `sexo` VARCHAR(45) NOT NULL,
  `datanascimento` DATE NOT NULL,
  `cpf` VARCHAR(11) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `happyPet`.`pedidos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `happyPet`.`pedidos` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `data` DATE NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  `clientes_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_pedidos_clientes1_idx` (`clientes_id` ASC),
  CONSTRAINT `fk_pedidos_clientes1`
    FOREIGN KEY (`clientes_id`)
    REFERENCES `happyPet`.`clientes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `happyPet`.`itensPedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `happyPet`.`itensPedido` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `quantidade` INT UNSIGNED NOT NULL,
  `valor` FLOAT UNSIGNED NOT NULL,
  `produtos_id` INT UNSIGNED NOT NULL,
  `pedidos_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_itensPedido_produtos1_idx` (`produtos_id` ASC),
  INDEX `fk_itensPedido_pedidos1_idx` (`pedidos_id` ASC),
  CONSTRAINT `fk_itensPedido_produtos1`
    FOREIGN KEY (`produtos_id`)
    REFERENCES `happyPet`.`produtos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_itensPedido_pedidos1`
    FOREIGN KEY (`pedidos_id`)
    REFERENCES `happyPet`.`pedidos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `happyPet`.`enderecos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `happyPet`.`enderecos` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `rua` VARCHAR(100) NOT NULL,
  `numero` VARCHAR(10) NOT NULL,
  `bairro` VARCHAR(100) NOT NULL,
  `complemento` VARCHAR(50) NULL,
  `cidade` VARCHAR(100) NOT NULL,
  `estado` VARCHAR(100) NOT NULL,
  `cep` VARCHAR(8) NOT NULL,
  `clientes_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_enderecos_clientes1_idx` (`clientes_id` ASC),
  CONSTRAINT `fk_enderecos_clientes1`
    FOREIGN KEY (`clientes_id`)
    REFERENCES `happyPet`.`clientes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `happyPet`.`imagensProdutos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `happyPet`.`imagensProdutos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `imagem` VARCHAR(250) NOT NULL,
  `produtos_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_imagensProdutos_produtos1_idx` (`produtos_id` ASC),
  CONSTRAINT `fk_imagensProdutos_produtos1`
    FOREIGN KEY (`produtos_id`)
    REFERENCES `happyPet`.`produtos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
